

[build]
target = ["x86_64-apple-darwin","x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu",
"aarch64-apple-darwin", "riscv64gc-unknown-linux-gnu",
"sparcv9-sun-solaris", "wasm32-unknown-unknown"]

[term]
verbose = true


